/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Wanderson
 */
public class Paciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Paciente
     */
    public Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpCadastrar = new javax.swing.JPanel();
        jpCamposCad = new javax.swing.JPanel();
        jlCpfCad = new javax.swing.JLabel();
        tfCpfCad = new javax.swing.JFormattedTextField();
        jlTelefoneCad = new javax.swing.JLabel();
        tfTelefoneCad = new javax.swing.JFormattedTextField();
        jlNomeCad = new javax.swing.JLabel();
        jlEnderecoCad = new javax.swing.JLabel();
        tfNomeCad = new javax.swing.JTextField();
        tfEnderecoCad = new javax.swing.JTextField();
        btnSalvarCad = new javax.swing.JButton();
        btnFecharCad = new javax.swing.JButton();
        jpConsultar = new javax.swing.JPanel();
        jpCamposCons = new javax.swing.JPanel();
        jlCpfCons = new javax.swing.JLabel();
        tfCpfCons = new javax.swing.JFormattedTextField();
        jlTelefoneCons = new javax.swing.JLabel();
        tfTelefoneCons = new javax.swing.JFormattedTextField();
        jlNomeCons = new javax.swing.JLabel();
        jlEnderecoCons = new javax.swing.JLabel();
        tfNomeCons = new javax.swing.JTextField();
        tfEnderecoCons = new javax.swing.JTextField();
        btnFecharCons = new javax.swing.JButton();
        cbxNomeCons = new javax.swing.JComboBox<>();
        jlSelecioneCons = new javax.swing.JLabel();
        jpAlterar = new javax.swing.JPanel();
        jpCamposAlt = new javax.swing.JPanel();
        jlCpfAlt = new javax.swing.JLabel();
        tfCpfAlt = new javax.swing.JFormattedTextField();
        jlTelefoneAlt = new javax.swing.JLabel();
        tfTelefoneAlt = new javax.swing.JFormattedTextField();
        jlNomeAlt = new javax.swing.JLabel();
        jlEnderecoAlt = new javax.swing.JLabel();
        tfNomeAlt = new javax.swing.JTextField();
        tfEnderecoAlt = new javax.swing.JTextField();
        btnSalvarAlt = new javax.swing.JButton();
        btnFecharAlt = new javax.swing.JButton();
        cbxNomeCons2 = new javax.swing.JComboBox<>();
        jlSelecioneCons2 = new javax.swing.JLabel();
        cbxNomeAlt = new javax.swing.JComboBox<>();
        jlSelecioneAlt = new javax.swing.JLabel();
        jpExcluir = new javax.swing.JPanel();
        jpCamposExc = new javax.swing.JPanel();
        jlCpfExc = new javax.swing.JLabel();
        tfCpfExc = new javax.swing.JFormattedTextField();
        jlTelefoneExc = new javax.swing.JLabel();
        tfTelefoneExc = new javax.swing.JFormattedTextField();
        jlNomeExc = new javax.swing.JLabel();
        jlEnderecoExc = new javax.swing.JLabel();
        tfNomeExc = new javax.swing.JTextField();
        tfEnderecoExc = new javax.swing.JTextField();
        btnSalvarExc = new javax.swing.JButton();
        btnFecharExc = new javax.swing.JButton();
        cbxNomeCons3 = new javax.swing.JComboBox<>();
        jlSelecioneCons3 = new javax.swing.JLabel();
        cbxNomeExc = new javax.swing.JComboBox<>();
        jlSelecioneExc = new javax.swing.JLabel();

        jlCpfCad.setText("CPF");

        try {
            tfCpfCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneCad.setText("Telefone");

        try {
            tfTelefoneCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeCad.setText("Nome");

        jlEnderecoCad.setText("Endereço");

        javax.swing.GroupLayout jpCamposCadLayout = new javax.swing.GroupLayout(jpCamposCad);
        jpCamposCad.setLayout(jpCamposCadLayout);
        jpCamposCadLayout.setHorizontalGroup(
            jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposCadLayout.createSequentialGroup()
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposCadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfCad)
                            .addComponent(jlNomeCad))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCamposCadLayout.createSequentialGroup()
                                .addComponent(tfCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jlTelefoneCad)
                                .addGap(35, 35, 35)
                                .addComponent(tfTelefoneCad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeCad)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposCadLayout.createSequentialGroup()
                        .addComponent(jlEnderecoCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoCad)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCamposCadLayout.setVerticalGroup(
            jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeCad)
                    .addComponent(tfNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneCad)
                    .addComponent(tfTelefoneCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfCad)
                    .addComponent(tfCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoCad)
                    .addComponent(tfEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvarCad.setText("Salvar");

        btnFecharCad.setText("Fechar");

        javax.swing.GroupLayout jpCadastrarLayout = new javax.swing.GroupLayout(jpCadastrar);
        jpCadastrar.setLayout(jpCadastrarLayout);
        jpCadastrarLayout.setHorizontalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastrarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnSalvarCad)
                .addGap(94, 94, 94)
                .addComponent(btnFecharCad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCadastrarLayout.setVerticalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jpCamposCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharCad)
                    .addComponent(btnSalvarCad))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", jpCadastrar);

        jlCpfCons.setText("CPF");

        try {
            tfCpfCons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneCons.setText("Telefone");

        try {
            tfTelefoneCons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeCons.setText("Nome");

        jlEnderecoCons.setText("Endereço");

        javax.swing.GroupLayout jpCamposConsLayout = new javax.swing.GroupLayout(jpCamposCons);
        jpCamposCons.setLayout(jpCamposConsLayout);
        jpCamposConsLayout.setHorizontalGroup(
            jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposConsLayout.createSequentialGroup()
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposConsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfCons)
                            .addComponent(jlNomeCons))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCamposConsLayout.createSequentialGroup()
                                .addComponent(tfCpfCons, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jlTelefoneCons)
                                .addGap(35, 35, 35)
                                .addComponent(tfTelefoneCons, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeCons)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposConsLayout.createSequentialGroup()
                        .addComponent(jlEnderecoCons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoCons)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCamposConsLayout.setVerticalGroup(
            jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposConsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeCons)
                    .addComponent(tfNomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneCons)
                    .addComponent(tfTelefoneCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfCons)
                    .addComponent(tfCpfCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoCons)
                    .addComponent(tfEnderecoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFecharCons.setText("Fechar");

        jlSelecioneCons.setText("Selecione");

        javax.swing.GroupLayout jpConsultarLayout = new javax.swing.GroupLayout(jpConsultar);
        jpConsultar.setLayout(jpConsultarLayout);
        jpConsultarLayout.setHorizontalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposCons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                        .addComponent(btnFecharCons)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                        .addComponent(jlSelecioneCons)
                        .addGap(30, 30, 30)
                        .addComponent(cbxNomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jpConsultarLayout.setVerticalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSelecioneCons))
                .addGap(47, 47, 47)
                .addComponent(jpCamposCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFecharCons)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jpConsultar);

        jlCpfAlt.setText("CPF");

        try {
            tfCpfAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneAlt.setText("Telefone");

        try {
            tfTelefoneAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeAlt.setText("Nome");

        jlEnderecoAlt.setText("Endereço");

        javax.swing.GroupLayout jpCamposAltLayout = new javax.swing.GroupLayout(jpCamposAlt);
        jpCamposAlt.setLayout(jpCamposAltLayout);
        jpCamposAltLayout.setHorizontalGroup(
            jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposAltLayout.createSequentialGroup()
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposAltLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfAlt)
                            .addComponent(jlNomeAlt))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCamposAltLayout.createSequentialGroup()
                                .addComponent(tfCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jlTelefoneAlt)
                                .addGap(35, 35, 35)
                                .addComponent(tfTelefoneAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeAlt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposAltLayout.createSequentialGroup()
                        .addComponent(jlEnderecoAlt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoAlt)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCamposAltLayout.setVerticalGroup(
            jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposAltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeAlt)
                    .addComponent(tfNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneAlt)
                    .addComponent(tfTelefoneAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfAlt)
                    .addComponent(tfCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoAlt)
                    .addComponent(tfEnderecoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvarAlt.setText("Salvar");

        btnFecharAlt.setText("Fechar");

        jlSelecioneCons2.setText("Selecione");

        jlSelecioneAlt.setText("Selecione");

        javax.swing.GroupLayout jpAlterarLayout = new javax.swing.GroupLayout(jpAlterar);
        jpAlterar.setLayout(jpAlterarLayout);
        jpAlterarLayout.setHorizontalGroup(
            jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpAlterarLayout.createSequentialGroup()
                .addGroup(jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAlterarLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnSalvarAlt)
                        .addGap(94, 94, 94)
                        .addComponent(btnFecharAlt))
                    .addGroup(jpAlterarLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jlSelecioneAlt)
                        .addGap(30, 30, 30)
                        .addComponent(cbxNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpAlterarLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jlSelecioneCons2)
                    .addGap(30, 30, 30)
                    .addComponent(cbxNomeCons2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );
        jpAlterarLayout.setVerticalGroup(
            jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSelecioneAlt))
                .addGap(47, 47, 47)
                .addComponent(jpCamposAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharAlt)
                    .addComponent(btnSalvarAlt))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpAlterarLayout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addGroup(jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxNomeCons2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlSelecioneCons2))
                    .addContainerGap(131, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Alterar", jpAlterar);

        jlCpfExc.setText("CPF");

        try {
            tfCpfExc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneExc.setText("Telefone");

        try {
            tfTelefoneExc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeExc.setText("Nome");

        jlEnderecoExc.setText("Endereço");

        javax.swing.GroupLayout jpCamposExcLayout = new javax.swing.GroupLayout(jpCamposExc);
        jpCamposExc.setLayout(jpCamposExcLayout);
        jpCamposExcLayout.setHorizontalGroup(
            jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposExcLayout.createSequentialGroup()
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposExcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfExc)
                            .addComponent(jlNomeExc))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCamposExcLayout.createSequentialGroup()
                                .addComponent(tfCpfExc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jlTelefoneExc)
                                .addGap(35, 35, 35)
                                .addComponent(tfTelefoneExc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeExc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposExcLayout.createSequentialGroup()
                        .addComponent(jlEnderecoExc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoExc)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCamposExcLayout.setVerticalGroup(
            jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposExcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeExc)
                    .addComponent(tfNomeExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneExc)
                    .addComponent(tfTelefoneExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfExc)
                    .addComponent(tfCpfExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoExc)
                    .addComponent(tfEnderecoExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvarExc.setText("Salvar");

        btnFecharExc.setText("Fechar");

        jlSelecioneCons3.setText("Selecione");

        jlSelecioneExc.setText("Selecione");

        javax.swing.GroupLayout jpExcluirLayout = new javax.swing.GroupLayout(jpExcluir);
        jpExcluir.setLayout(jpExcluirLayout);
        jpExcluirLayout.setHorizontalGroup(
            jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposExc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpExcluirLayout.createSequentialGroup()
                .addGroup(jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpExcluirLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnSalvarExc)
                        .addGap(94, 94, 94)
                        .addComponent(btnFecharExc))
                    .addGroup(jpExcluirLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jlSelecioneExc)
                        .addGap(30, 30, 30)
                        .addComponent(cbxNomeExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpExcluirLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jlSelecioneCons3)
                    .addGap(30, 30, 30)
                    .addComponent(cbxNomeCons3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );
        jpExcluirLayout.setVerticalGroup(
            jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNomeExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSelecioneExc))
                .addGap(47, 47, 47)
                .addComponent(jpCamposExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharExc)
                    .addComponent(btnSalvarExc))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpExcluirLayout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addGroup(jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxNomeCons3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlSelecioneCons3))
                    .addContainerGap(131, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Excluir", jpExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharAlt;
    private javax.swing.JButton btnFecharCad;
    private javax.swing.JButton btnFecharCons;
    private javax.swing.JButton btnFecharExc;
    private javax.swing.JButton btnSalvarAlt;
    private javax.swing.JButton btnSalvarCad;
    private javax.swing.JButton btnSalvarExc;
    private javax.swing.JComboBox<String> cbxNomeAlt;
    private javax.swing.JComboBox<String> cbxNomeCons;
    private javax.swing.JComboBox<String> cbxNomeCons2;
    private javax.swing.JComboBox<String> cbxNomeCons3;
    private javax.swing.JComboBox<String> cbxNomeExc;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlCpfAlt;
    private javax.swing.JLabel jlCpfCad;
    private javax.swing.JLabel jlCpfCad1;
    private javax.swing.JLabel jlCpfCad10;
    private javax.swing.JLabel jlCpfCad11;
    private javax.swing.JLabel jlCpfCad12;
    private javax.swing.JLabel jlCpfCad13;
    private javax.swing.JLabel jlCpfCad14;
    private javax.swing.JLabel jlCpfCad2;
    private javax.swing.JLabel jlCpfCad3;
    private javax.swing.JLabel jlCpfCad4;
    private javax.swing.JLabel jlCpfCad5;
    private javax.swing.JLabel jlCpfCad6;
    private javax.swing.JLabel jlCpfCad7;
    private javax.swing.JLabel jlCpfCad8;
    private javax.swing.JLabel jlCpfCad9;
    private javax.swing.JLabel jlCpfCons;
    private javax.swing.JLabel jlCpfExc;
    private javax.swing.JLabel jlEnderecoAlt;
    private javax.swing.JLabel jlEnderecoCad;
    private javax.swing.JLabel jlEnderecoCad1;
    private javax.swing.JLabel jlEnderecoCad10;
    private javax.swing.JLabel jlEnderecoCad11;
    private javax.swing.JLabel jlEnderecoCad12;
    private javax.swing.JLabel jlEnderecoCad13;
    private javax.swing.JLabel jlEnderecoCad14;
    private javax.swing.JLabel jlEnderecoCad2;
    private javax.swing.JLabel jlEnderecoCad3;
    private javax.swing.JLabel jlEnderecoCad4;
    private javax.swing.JLabel jlEnderecoCad5;
    private javax.swing.JLabel jlEnderecoCad6;
    private javax.swing.JLabel jlEnderecoCad7;
    private javax.swing.JLabel jlEnderecoCad8;
    private javax.swing.JLabel jlEnderecoCad9;
    private javax.swing.JLabel jlEnderecoCons;
    private javax.swing.JLabel jlEnderecoExc;
    private javax.swing.JLabel jlNomeAlt;
    private javax.swing.JLabel jlNomeCad;
    private javax.swing.JLabel jlNomeCad1;
    private javax.swing.JLabel jlNomeCad10;
    private javax.swing.JLabel jlNomeCad11;
    private javax.swing.JLabel jlNomeCad12;
    private javax.swing.JLabel jlNomeCad13;
    private javax.swing.JLabel jlNomeCad14;
    private javax.swing.JLabel jlNomeCad2;
    private javax.swing.JLabel jlNomeCad3;
    private javax.swing.JLabel jlNomeCad4;
    private javax.swing.JLabel jlNomeCad5;
    private javax.swing.JLabel jlNomeCad6;
    private javax.swing.JLabel jlNomeCad7;
    private javax.swing.JLabel jlNomeCad8;
    private javax.swing.JLabel jlNomeCad9;
    private javax.swing.JLabel jlNomeCons;
    private javax.swing.JLabel jlNomeExc;
    private javax.swing.JLabel jlSelecioneAlt;
    private javax.swing.JLabel jlSelecioneCons;
    private javax.swing.JLabel jlSelecioneCons2;
    private javax.swing.JLabel jlSelecioneCons3;
    private javax.swing.JLabel jlSelecioneExc;
    private javax.swing.JLabel jlTelefoneAlt;
    private javax.swing.JLabel jlTelefoneCad;
    private javax.swing.JLabel jlTelefoneCad1;
    private javax.swing.JLabel jlTelefoneCad10;
    private javax.swing.JLabel jlTelefoneCad11;
    private javax.swing.JLabel jlTelefoneCad12;
    private javax.swing.JLabel jlTelefoneCad13;
    private javax.swing.JLabel jlTelefoneCad14;
    private javax.swing.JLabel jlTelefoneCad2;
    private javax.swing.JLabel jlTelefoneCad3;
    private javax.swing.JLabel jlTelefoneCad4;
    private javax.swing.JLabel jlTelefoneCad5;
    private javax.swing.JLabel jlTelefoneCad6;
    private javax.swing.JLabel jlTelefoneCad7;
    private javax.swing.JLabel jlTelefoneCad8;
    private javax.swing.JLabel jlTelefoneCad9;
    private javax.swing.JLabel jlTelefoneCons;
    private javax.swing.JLabel jlTelefoneExc;
    private javax.swing.JPanel jpAlterar;
    private javax.swing.JPanel jpCadastrar;
    private javax.swing.JPanel jpCamposAlt;
    private javax.swing.JPanel jpCamposCad;
    private javax.swing.JPanel jpCamposCons;
    private javax.swing.JPanel jpCamposExc;
    private javax.swing.JPanel jpConsultar;
    private javax.swing.JPanel jpExcluir;
    private javax.swing.JFormattedTextField tfCpfAlt;
    private javax.swing.JFormattedTextField tfCpfCad;
    private javax.swing.JFormattedTextField tfCpfCad1;
    private javax.swing.JFormattedTextField tfCpfCad10;
    private javax.swing.JFormattedTextField tfCpfCad11;
    private javax.swing.JFormattedTextField tfCpfCad12;
    private javax.swing.JFormattedTextField tfCpfCad13;
    private javax.swing.JFormattedTextField tfCpfCad14;
    private javax.swing.JFormattedTextField tfCpfCad2;
    private javax.swing.JFormattedTextField tfCpfCad3;
    private javax.swing.JFormattedTextField tfCpfCad4;
    private javax.swing.JFormattedTextField tfCpfCad5;
    private javax.swing.JFormattedTextField tfCpfCad6;
    private javax.swing.JFormattedTextField tfCpfCad7;
    private javax.swing.JFormattedTextField tfCpfCad8;
    private javax.swing.JFormattedTextField tfCpfCad9;
    private javax.swing.JFormattedTextField tfCpfCons;
    private javax.swing.JFormattedTextField tfCpfExc;
    private javax.swing.JTextField tfEnderecoAlt;
    private javax.swing.JTextField tfEnderecoCad;
    private javax.swing.JTextField tfEnderecoCad1;
    private javax.swing.JTextField tfEnderecoCad10;
    private javax.swing.JTextField tfEnderecoCad11;
    private javax.swing.JTextField tfEnderecoCad12;
    private javax.swing.JTextField tfEnderecoCad13;
    private javax.swing.JTextField tfEnderecoCad14;
    private javax.swing.JTextField tfEnderecoCad2;
    private javax.swing.JTextField tfEnderecoCad3;
    private javax.swing.JTextField tfEnderecoCad4;
    private javax.swing.JTextField tfEnderecoCad5;
    private javax.swing.JTextField tfEnderecoCad6;
    private javax.swing.JTextField tfEnderecoCad7;
    private javax.swing.JTextField tfEnderecoCad8;
    private javax.swing.JTextField tfEnderecoCad9;
    private javax.swing.JTextField tfEnderecoCons;
    private javax.swing.JTextField tfEnderecoExc;
    private javax.swing.JTextField tfNomeAlt;
    private javax.swing.JTextField tfNomeCad;
    private javax.swing.JTextField tfNomeCad1;
    private javax.swing.JTextField tfNomeCad10;
    private javax.swing.JTextField tfNomeCad11;
    private javax.swing.JTextField tfNomeCad12;
    private javax.swing.JTextField tfNomeCad13;
    private javax.swing.JTextField tfNomeCad14;
    private javax.swing.JTextField tfNomeCad2;
    private javax.swing.JTextField tfNomeCad3;
    private javax.swing.JTextField tfNomeCad4;
    private javax.swing.JTextField tfNomeCad5;
    private javax.swing.JTextField tfNomeCad6;
    private javax.swing.JTextField tfNomeCad7;
    private javax.swing.JTextField tfNomeCad8;
    private javax.swing.JTextField tfNomeCad9;
    private javax.swing.JTextField tfNomeCons;
    private javax.swing.JTextField tfNomeExc;
    private javax.swing.JFormattedTextField tfTelefoneAlt;
    private javax.swing.JFormattedTextField tfTelefoneCad;
    private javax.swing.JFormattedTextField tfTelefoneCad1;
    private javax.swing.JFormattedTextField tfTelefoneCad10;
    private javax.swing.JFormattedTextField tfTelefoneCad11;
    private javax.swing.JFormattedTextField tfTelefoneCad12;
    private javax.swing.JFormattedTextField tfTelefoneCad13;
    private javax.swing.JFormattedTextField tfTelefoneCad14;
    private javax.swing.JFormattedTextField tfTelefoneCad2;
    private javax.swing.JFormattedTextField tfTelefoneCad3;
    private javax.swing.JFormattedTextField tfTelefoneCad4;
    private javax.swing.JFormattedTextField tfTelefoneCad5;
    private javax.swing.JFormattedTextField tfTelefoneCad6;
    private javax.swing.JFormattedTextField tfTelefoneCad7;
    private javax.swing.JFormattedTextField tfTelefoneCad8;
    private javax.swing.JFormattedTextField tfTelefoneCad9;
    private javax.swing.JFormattedTextField tfTelefoneCons;
    private javax.swing.JFormattedTextField tfTelefoneExc;
    // End of variables declaration//GEN-END:variables
}
