/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.PacienteDao;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Opcao;
import model.PacienteModel;

/**
 *
 * @author Wanderson
 */
public class Paciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Paciente
     */
    Opcao opcao;
    PacienteDao pacienteDao;
    ArrayList<PacienteModel> pacientes;

    public Paciente() {
        initComponents();
        jTabbedPane1.setEnabled(false);
        pacienteDao = new PacienteDao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpCadastrar = new javax.swing.JPanel();
        jpCamposCad = new javax.swing.JPanel();
        jlCpfCad = new javax.swing.JLabel();
        tfCpfCad = new javax.swing.JFormattedTextField();
        jlTelefoneCad = new javax.swing.JLabel();
        tfTelefoneCad = new javax.swing.JFormattedTextField();
        jlNomeCad = new javax.swing.JLabel();
        jlEnderecoCad = new javax.swing.JLabel();
        tfNomeCad = new javax.swing.JTextField();
        tfEnderecoCad = new javax.swing.JTextField();
        btnSalvarCad = new javax.swing.JButton();
        btnFecharCad = new javax.swing.JButton();
        jpConsultar = new javax.swing.JPanel();
        jpCamposCons = new javax.swing.JPanel();
        jlCpfCons = new javax.swing.JLabel();
        tfCpfCons = new javax.swing.JFormattedTextField();
        jlTelefoneCons = new javax.swing.JLabel();
        tfTelefoneCons = new javax.swing.JFormattedTextField();
        jlNomeCons = new javax.swing.JLabel();
        jlEnderecoCons = new javax.swing.JLabel();
        tfNomeCons = new javax.swing.JTextField();
        tfEnderecoCons = new javax.swing.JTextField();
        btnFecharCons = new javax.swing.JButton();
        cbxNomeCons = new javax.swing.JComboBox<>();
        jpAlterar = new javax.swing.JPanel();
        jpCamposAlt = new javax.swing.JPanel();
        jlCpfAlt = new javax.swing.JLabel();
        tfCpfAlt = new javax.swing.JFormattedTextField();
        jlTelefoneAlt = new javax.swing.JLabel();
        tfTelefoneAlt = new javax.swing.JFormattedTextField();
        jlNomeAlt = new javax.swing.JLabel();
        jlEnderecoAlt = new javax.swing.JLabel();
        tfNomeAlt = new javax.swing.JTextField();
        tfEnderecoAlt = new javax.swing.JTextField();
        btnSalvarAlt = new javax.swing.JButton();
        btnFecharAlt = new javax.swing.JButton();
        cbxNomeAlt = new javax.swing.JComboBox<>();
        jpExcluir = new javax.swing.JPanel();
        jpCamposExc = new javax.swing.JPanel();
        jlCpfExc = new javax.swing.JLabel();
        tfCpfExc = new javax.swing.JFormattedTextField();
        jlTelefoneExc = new javax.swing.JLabel();
        tfTelefoneExc = new javax.swing.JFormattedTextField();
        jlNomeExc = new javax.swing.JLabel();
        jlEnderecoExc = new javax.swing.JLabel();
        tfNomeExc = new javax.swing.JTextField();
        tfEnderecoExc = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnFecharExc = new javax.swing.JButton();
        cbxNomeExc = new javax.swing.JComboBox<>();

        setTitle("Paciente");
        setDoubleBuffered(true);

        jpCadastrar.setDoubleBuffered(false);
        jpCadastrar.setEnabled(false);

        jlCpfCad.setText("CPF");

        try {
            tfCpfCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneCad.setText("Telefone");

        try {
            tfTelefoneCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeCad.setText("Nome");

        jlEnderecoCad.setText("Endereço");

        javax.swing.GroupLayout jpCamposCadLayout = new javax.swing.GroupLayout(jpCamposCad);
        jpCamposCad.setLayout(jpCamposCadLayout);
        jpCamposCadLayout.setHorizontalGroup(
            jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposCadLayout.createSequentialGroup()
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposCadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfCad)
                            .addComponent(jlNomeCad))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCamposCadLayout.createSequentialGroup()
                                .addComponent(tfCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jlTelefoneCad)
                                .addGap(35, 35, 35)
                                .addComponent(tfTelefoneCad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeCad)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposCadLayout.createSequentialGroup()
                        .addComponent(jlEnderecoCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoCad)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCamposCadLayout.setVerticalGroup(
            jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeCad)
                    .addComponent(tfNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneCad)
                    .addComponent(tfTelefoneCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfCad)
                    .addComponent(tfCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoCad)
                    .addComponent(tfEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvarCad.setText("Salvar");
        btnSalvarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadActionPerformed(evt);
            }
        });

        btnFecharCad.setText("Fechar");
        btnFecharCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastrarLayout = new javax.swing.GroupLayout(jpCadastrar);
        jpCadastrar.setLayout(jpCadastrarLayout);
        jpCadastrarLayout.setHorizontalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastrarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnSalvarCad)
                .addGap(94, 94, 94)
                .addComponent(btnFecharCad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCadastrarLayout.setVerticalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jpCamposCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharCad)
                    .addComponent(btnSalvarCad))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", jpCadastrar);

        jlCpfCons.setText("CPF");

        tfCpfCons.setEditable(false);
        try {
            tfCpfCons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneCons.setText("Telefone");

        tfTelefoneCons.setEditable(false);
        try {
            tfTelefoneCons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeCons.setText("Nome");

        jlEnderecoCons.setText("Endereço");

        tfNomeCons.setEditable(false);

        tfEnderecoCons.setEditable(false);

        javax.swing.GroupLayout jpCamposConsLayout = new javax.swing.GroupLayout(jpCamposCons);
        jpCamposCons.setLayout(jpCamposConsLayout);
        jpCamposConsLayout.setHorizontalGroup(
            jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposConsLayout.createSequentialGroup()
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposConsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfCons)
                            .addComponent(jlNomeCons))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCamposConsLayout.createSequentialGroup()
                                .addComponent(tfCpfCons, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jlTelefoneCons)
                                .addGap(30, 30, 30)
                                .addComponent(tfTelefoneCons, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposConsLayout.createSequentialGroup()
                        .addComponent(jlEnderecoCons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoCons)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCamposConsLayout.setVerticalGroup(
            jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposConsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeCons)
                    .addComponent(tfNomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneCons)
                    .addComponent(tfTelefoneCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfCons)
                    .addComponent(tfCpfCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoCons)
                    .addComponent(tfEnderecoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFecharCons.setText("Fechar");
        btnFecharCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharConsActionPerformed(evt);
            }
        });

        cbxNomeCons.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNomeConsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpConsultarLayout = new javax.swing.GroupLayout(jpConsultar);
        jpConsultar.setLayout(jpConsultarLayout);
        jpConsultarLayout.setHorizontalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposCons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                        .addComponent(btnFecharCons)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                        .addComponent(cbxNomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        jpConsultarLayout.setVerticalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxNomeCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jpCamposCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFecharCons)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jpConsultar);

        jlCpfAlt.setText("CPF");

        try {
            tfCpfAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneAlt.setText("Telefone");

        try {
            tfTelefoneAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeAlt.setText("Nome");

        jlEnderecoAlt.setText("Endereço");

        javax.swing.GroupLayout jpCamposAltLayout = new javax.swing.GroupLayout(jpCamposAlt);
        jpCamposAlt.setLayout(jpCamposAltLayout);
        jpCamposAltLayout.setHorizontalGroup(
            jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposAltLayout.createSequentialGroup()
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposAltLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfAlt)
                            .addComponent(jlNomeAlt))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCamposAltLayout.createSequentialGroup()
                                .addComponent(tfCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jlTelefoneAlt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfTelefoneAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposAltLayout.createSequentialGroup()
                        .addComponent(jlEnderecoAlt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoAlt)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCamposAltLayout.setVerticalGroup(
            jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposAltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeAlt)
                    .addComponent(tfNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneAlt)
                    .addComponent(tfTelefoneAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfAlt)
                    .addComponent(tfCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoAlt)
                    .addComponent(tfEnderecoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvarAlt.setText("Salvar");
        btnSalvarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAltActionPerformed(evt);
            }
        });

        btnFecharAlt.setText("Fechar");
        btnFecharAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharAltActionPerformed(evt);
            }
        });

        cbxNomeAlt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNomeAltItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpAlterarLayout = new javax.swing.GroupLayout(jpAlterar);
        jpAlterar.setLayout(jpAlterarLayout);
        jpAlterarLayout.setHorizontalGroup(
            jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpAlterarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnSalvarAlt)
                .addGap(94, 94, 94)
                .addComponent(btnFecharAlt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jpAlterarLayout.setVerticalGroup(
            jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jpCamposAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharAlt)
                    .addComponent(btnSalvarAlt))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alterar", jpAlterar);

        jlCpfExc.setText("CPF");

        tfCpfExc.setEditable(false);
        try {
            tfCpfExc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlTelefoneExc.setText("Telefone");

        tfTelefoneExc.setEditable(false);
        try {
            tfTelefoneExc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlNomeExc.setText("Nome");

        jlEnderecoExc.setText("Endereço");

        tfNomeExc.setEditable(false);

        tfEnderecoExc.setEditable(false);

        javax.swing.GroupLayout jpCamposExcLayout = new javax.swing.GroupLayout(jpCamposExc);
        jpCamposExc.setLayout(jpCamposExcLayout);
        jpCamposExcLayout.setHorizontalGroup(
            jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposExcLayout.createSequentialGroup()
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposExcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpfExc)
                            .addComponent(jlNomeExc))
                        .addGap(22, 22, 22)
                        .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCamposExcLayout.createSequentialGroup()
                                .addComponent(tfCpfExc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jlTelefoneExc)
                                .addGap(28, 28, 28)
                                .addComponent(tfTelefoneExc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeExc, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposExcLayout.createSequentialGroup()
                        .addComponent(jlEnderecoExc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnderecoExc)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpCamposExcLayout.setVerticalGroup(
            jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposExcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeExc)
                    .addComponent(tfNomeExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneExc)
                    .addComponent(tfTelefoneExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfExc)
                    .addComponent(tfCpfExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCamposExcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEnderecoExc)
                    .addComponent(tfEnderecoExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFecharExc.setText("Fechar");
        btnFecharExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharExcActionPerformed(evt);
            }
        });

        cbxNomeExc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNomeExcItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpExcluirLayout = new javax.swing.GroupLayout(jpExcluir);
        jpExcluir.setLayout(jpExcluirLayout);
        jpExcluirLayout.setHorizontalGroup(
            jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamposExc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpExcluirLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnExcluir)
                .addGap(94, 94, 94)
                .addComponent(btnFecharExc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExcluirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxNomeExc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jpExcluirLayout.setVerticalGroup(
            jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxNomeExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jpCamposExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharExc)
                    .addComponent(btnExcluir))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Excluir", jpExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadActionPerformed
        int quat = VerificaCampos(jpCamposCad);
        if (quat == 0) {
            PacienteModel paciente = new PacienteModel(tfCpfCad.getText(), tfNomeCad.getText(),
                    tfEnderecoCad.getText(), tfTelefoneCad.getText());
            int ret = pacienteDao.cadastrar(paciente);
            if (ret == 1) {
                JOptionPane.showConfirmDialog(this, "Cadastrado com sucesso !", "Cadastrar", JOptionPane.DEFAULT_OPTION);
                if (JOptionPane.DEFAULT_OPTION == -1) {
                    dispose();
                }
            }

        } else {
            JOptionPane.showMessageDialog(jpCamposCad, "Preencha todos os campos !");
        }


    }//GEN-LAST:event_btnSalvarCadActionPerformed

    private void cbxNomeConsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNomeConsItemStateChanged
        tfCpfCons.setText(pacientes.get(cbxNomeCons.getSelectedIndex()).getCpf());
        tfNomeCons.setText(pacientes.get(cbxNomeCons.getSelectedIndex()).getNome());
        tfEnderecoCons.setText(pacientes.get(cbxNomeCons.getSelectedIndex()).getEndereco());
        tfTelefoneCons.setText(pacientes.get(cbxNomeCons.getSelectedIndex()).getTelefone());

    }//GEN-LAST:event_cbxNomeConsItemStateChanged

    private void cbxNomeAltItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNomeAltItemStateChanged
        tfCpfAlt.setText(pacientes.get(cbxNomeAlt.getSelectedIndex()).getCpf());
        tfNomeAlt.setText(pacientes.get(cbxNomeAlt.getSelectedIndex()).getNome());
        tfEnderecoAlt.setText(pacientes.get(cbxNomeAlt.getSelectedIndex()).getEndereco());
        tfTelefoneAlt.setText(pacientes.get(cbxNomeAlt.getSelectedIndex()).getTelefone());
    }//GEN-LAST:event_cbxNomeAltItemStateChanged

    private void cbxNomeExcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNomeExcItemStateChanged
        tfCpfExc.setText(pacientes.get(cbxNomeExc.getSelectedIndex()).getCpf());
        tfNomeExc.setText(pacientes.get(cbxNomeExc.getSelectedIndex()).getNome());
        tfEnderecoExc.setText(pacientes.get(cbxNomeExc.getSelectedIndex()).getEndereco());
        tfTelefoneExc.setText(pacientes.get(cbxNomeExc.getSelectedIndex()).getTelefone());    }//GEN-LAST:event_cbxNomeExcItemStateChanged

    private void btnFecharConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharConsActionPerformed
        fechar();
    }//GEN-LAST:event_btnFecharConsActionPerformed

    private void btnFecharAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharAltActionPerformed
        fechar();
    }//GEN-LAST:event_btnFecharAltActionPerformed

    private void btnFecharExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharExcActionPerformed
        fechar();
    }//GEN-LAST:event_btnFecharExcActionPerformed

    private void btnFecharCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCadActionPerformed
        fechar();
    }//GEN-LAST:event_btnFecharCadActionPerformed

    private void btnSalvarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAltActionPerformed
        PacienteModel paciente = pacientes.get(cbxNomeAlt.getSelectedIndex());
        paciente.setCpf(tfCpfAlt.getText());
        paciente.setNome(tfNomeAlt.getText());
        paciente.setEndereco(tfEnderecoAlt.getText());
        paciente.setTelefone(tfTelefoneAlt.getText());
        int ret = pacienteDao.alterar(paciente);
        if (ret == 1) {
            JOptionPane.showConfirmDialog(this, "Alterado com sucesso !", "Alterar", JOptionPane.DEFAULT_OPTION);
            if (JOptionPane.DEFAULT_OPTION == -1) {
                dispose();
            }
        }


    }//GEN-LAST:event_btnSalvarAltActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int op = JOptionPane.showInternalConfirmDialog(this, "Quer mesmo Excluir ?", "Excluir",
                JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            PacienteModel paciente = pacientes.get(cbxNomeExc.getSelectedIndex());
            int ret = pacienteDao.excluir(paciente);
            if (ret == 1) {
                JOptionPane.showConfirmDialog(this, "Excluido com sucesso !", "Excluir", JOptionPane.DEFAULT_OPTION);
                if (JOptionPane.DEFAULT_OPTION == -1) {
                    dispose();
                }
            }
            dispose();
        }    }//GEN-LAST:event_btnExcluirActionPerformed

    public void selecionado(Opcao op) {
        if (op == opcao.CADASTRAR) {
            jTabbedPane1.setSelectedIndex(0);
        }
        if (op == opcao.CONSULTAR) {
            jTabbedPane1.setSelectedIndex(1);
            pacientes = pacienteDao.listar();
            carregaCampos(cbxNomeCons);

        }
        if (op == opcao.ALTERAR) {
            jTabbedPane1.setSelectedIndex(2);
            pacientes = pacienteDao.listar();
            carregaCampos(cbxNomeAlt);
            if (pacientes == null || pacientes.isEmpty()) {
                btnSalvarAlt.setEnabled(false);
            } else {
                btnSalvarAlt.setEnabled(true);
            }

        }
        if (op == opcao.EXCLUIR) {
            jTabbedPane1.setSelectedIndex(3);
            pacientes = pacienteDao.listar();
            carregaCampos(cbxNomeExc);
            if (pacientes == null || pacientes.isEmpty()) {
                btnExcluir.setEnabled(false);
            } else {
                btnExcluir.setEnabled(true);
            }

        }
    }

    public void limparCampos(JPanel jpanel) {
        Component[] com = jpanel.getComponents();
        for (Component component : com) {
            if (component instanceof JTextField) {
                JTextField tf = (JTextField) component;
                tf.setText("");

            }
        }

    }

    public void habilitarCampos(JPanel jpanel, boolean habilita) {
        Component[] com = jpanel.getComponents();
        for (Component component : com) {
            if (component instanceof JTextField) {
                JTextField tf = (JTextField) component;
                tf.setEnabled(habilita);

            }
        }

    }

    public int VerificaCampos(JPanel jpanel) {
        Component[] com = jpanel.getComponents();
        int cont = 0;
        for (Component component : com) {
            if (component instanceof JFormattedTextField) {
                JTextField tf = (JTextField) component;
                if (tf.getText().trim().charAt(0) == '.') {

                    cont += 1;
                } else {
                    if (tf.getText().trim().charAt(1) == ' ') {
                        cont += 1;
                       

                    }

                }

            } else {
                if (component instanceof JTextField) {
                    JTextField tf = (JTextField) component;
                    if (tf.getText().isEmpty()) {
                        cont += 1;
                    }
                }
            }

        }

        String telefone = tfTelefoneCad.getText().trim();

        System.out.println("Q: " + cont);

        return cont;
    }

    public void fechar() {
        int op = JOptionPane.showInternalConfirmDialog(this, "Quer mesmo Fechar ?", "Fechar",
                JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    public void carregaCampos(JComboBox cbx) {

        if (pacientes == null || pacientes.isEmpty()) {
        } else {

            for (PacienteModel paciente : pacientes) {
                cbx.addItem(paciente.getNome());
            }

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFecharAlt;
    private javax.swing.JButton btnFecharCad;
    private javax.swing.JButton btnFecharCons;
    private javax.swing.JButton btnFecharExc;
    private javax.swing.JButton btnSalvarAlt;
    private javax.swing.JButton btnSalvarCad;
    private javax.swing.JComboBox<String> cbxNomeAlt;
    private javax.swing.JComboBox<String> cbxNomeCons;
    private javax.swing.JComboBox<String> cbxNomeExc;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlCpfAlt;
    private javax.swing.JLabel jlCpfCad;
    private javax.swing.JLabel jlCpfCons;
    private javax.swing.JLabel jlCpfExc;
    private javax.swing.JLabel jlEnderecoAlt;
    private javax.swing.JLabel jlEnderecoCad;
    private javax.swing.JLabel jlEnderecoCons;
    private javax.swing.JLabel jlEnderecoExc;
    private javax.swing.JLabel jlNomeAlt;
    private javax.swing.JLabel jlNomeCad;
    private javax.swing.JLabel jlNomeCons;
    private javax.swing.JLabel jlNomeExc;
    private javax.swing.JLabel jlTelefoneAlt;
    private javax.swing.JLabel jlTelefoneCad;
    private javax.swing.JLabel jlTelefoneCons;
    private javax.swing.JLabel jlTelefoneExc;
    private javax.swing.JPanel jpAlterar;
    private javax.swing.JPanel jpCadastrar;
    private javax.swing.JPanel jpCamposAlt;
    private javax.swing.JPanel jpCamposCad;
    private javax.swing.JPanel jpCamposCons;
    private javax.swing.JPanel jpCamposExc;
    private javax.swing.JPanel jpConsultar;
    private javax.swing.JPanel jpExcluir;
    private javax.swing.JFormattedTextField tfCpfAlt;
    private javax.swing.JFormattedTextField tfCpfCad;
    private javax.swing.JFormattedTextField tfCpfCons;
    private javax.swing.JFormattedTextField tfCpfExc;
    private javax.swing.JTextField tfEnderecoAlt;
    private javax.swing.JTextField tfEnderecoCad;
    private javax.swing.JTextField tfEnderecoCons;
    private javax.swing.JTextField tfEnderecoExc;
    private javax.swing.JTextField tfNomeAlt;
    private javax.swing.JTextField tfNomeCad;
    private javax.swing.JTextField tfNomeCons;
    private javax.swing.JTextField tfNomeExc;
    private javax.swing.JFormattedTextField tfTelefoneAlt;
    private javax.swing.JFormattedTextField tfTelefoneCad;
    private javax.swing.JFormattedTextField tfTelefoneCons;
    private javax.swing.JFormattedTextField tfTelefoneExc;
    // End of variables declaration//GEN-END:variables
}
